/** Blinkit customer-web baseline tokens - synced from tools/blinkit-login-capture/out/extracted/design-tokens.json */
export const blinkitTokens = {
  brandYellow: '#F8CB46',
  brandYellowHover: '#F0C033',
  cartGreen: '#0C831F',
  cartGreenHover: '#097019',
  cartGreenDisabled: '#CCCCCC',
  text: '#1F1F1F',
  textDark: '#333333',
  textMuted: '#363636',
  textGray: '#666666',
  placeholder: '#999999',
  searchBg: '#F8F8F8',
  searchBorder: '#E8E8E8',
  divider: '#EEEEEE',
  dividerSoft: '#F2F2F2',
  headerHover: '#FCFCFC',
  surface: '#FFFFFF',
  pageBg: '#FFFFFF',
  footerBand: '#FBFBFB',
  disabledBtn: '#9C9C9C',
  overlayLogin: 'rgba(0,0,0,0.7)',
  radiusSearch: 12,
  radiusLogin: 16,
  /** Live Blinkit Okra (captured woff2) + Plus Jakarta fallback */
  fontFamily: 'Okra',
  fontSizes: {
    loginTitle: 24,
    loginSubtitle: 16,
    loginInput: 14,
    loginButton: 14,
    loginTerms: 12,
    locationTitle: 16,
    locationTitleDesktop: 18,
    locationSubtitle: 13,
    profile: 18,
    cart: 14,
    cartIcon: 28,
  },
  spacing: {
    headerHeightDesktop: 86,
    headerHeightMobile: 68,
    logoWidth: 178,
    locationWidth: 320,
    profileWidth: 162,
    cartWidth: 112,
    cartHeight: 52,
    loginWidth: 570,
    loginGap: 15,
    loginPadTop: 20,
    loginButtonMinHeight: 50,
    loginButtonWidth: 300,
    breakpointMobile: 1020,
  },
  headerHeightDesktop: 86,
  headerHeightMobile: 68,
  defaultStore: {
    lat: 12.9716,
    lng: 77.5946,
    label: 'Bangalore',
    fullAddress: 'MG Road, Bangalore',
    etaMinutes: 8,
  },
} as const;
