import {
  LayoutDashboard,
  Users,
  Package,
  ShoppingCart,
  Tag,
  CreditCard,
  BarChart3,
  Headphones,
  Settings,
  ScrollText,
  UserCircle,
  Bike,
  UserCog,
  Shield,
  FolderTree,
  Layers,
  Boxes,
  Award,
  Warehouse,
  GitBranch,
  RotateCcw,
  XCircle,
  Undo2,
  AlertTriangle,
  Ticket,
  Image,
  Zap,
  Wallet,
  TrendingUp,
  LineChart,
  UsersRound,
  PackageSearch,
  Store,
  Languages,
  type LucideIcon,
} from 'lucide-react';

const ICON_MAP: Record<string, LucideIcon> = {
  '/dashboard': LayoutDashboard,
  '/users': Users,
  '/users/customers': UserCircle,
  '/users/delivery-partners': Bike,
  '/users/store-managers': UserCog,
  '/users/admin-roles': Shield,
  '/catalog': Package,
  '/catalog/categories': FolderTree,
  '/catalog/sub-categories': Layers,
  '/catalog/products': Boxes,
  '/catalog/brands': Award,
  '/catalog/inventory': Warehouse,
  '/catalog/variants': GitBranch,
  '/orders': ShoppingCart,
  '/orders/refunds': RotateCcw,
  '/orders/cancellations': XCircle,
  '/orders/returns': Undo2,
  '/orders/disputes': AlertTriangle,
  '/promotions': Tag,
  '/promotions/coupons': Ticket,
  '/promotions/banners': Image,
  '/promotions/deals': Zap,
  '/payments': CreditCard,
  '/payments/reconciliation': BarChart3,
  '/payments/refunds': RotateCcw,
  '/payments/wallet': Wallet,
  '/reports': BarChart3,
  '/reports/sales': TrendingUp,
  '/reports/revenue': LineChart,
  '/reports/order-trends': BarChart3,
  '/reports/customer-retention': UsersRound,
  '/reports/product-performance': PackageSearch,
  '/reports/inventory': Warehouse,
  '/support/tickets': Headphones,
  '/settings': Settings,
  '/settings/store-details': Store,
  '/settings/roles-permissions': Shield,
  '/settings/languages': Languages,
  '/audit-logs': ScrollText,
};

export function getNavIcon(href: string): LucideIcon {
  return ICON_MAP[href] || LayoutDashboard;
}
